---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ scerets.DOCKERHUB_USER }}
          password: ${{ scerets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: docker/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Linting
        uses: docker-compose run --rm app sh -c "flake8"